# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-30 20:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='q_img',
        ),
    ]
