# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-30 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apage', '0002_remove_quote_q_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='tag',
        ),
        migrations.AlterField(
            model_name='quote',
            name='text',
            field=models.CharField(max_length=100),
        ),
    ]
