# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-30 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apage', '0003_auto_20171130_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='artist',
            field=models.CharField(default='Anonumous', max_length=100),
        ),
        migrations.AddField(
            model_name='quote',
            name='tag',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='quote',
            name='text',
            field=models.CharField(max_length=3000),
        ),
    ]
